apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wvvq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wvvq
    app.kubernetes.io/part-of: load-app-89b6afed-07cd-44a1-a6e2-cd64c48c9d36
  name: devfile-sample-wvvq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-wvvq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-wvvq
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-96-tenant/load-app-89b6afed-07cd-44a1-a6e2-cd64c48c9d36/devfile-sample-wvvq@sha256:6850651d197d7b7e3ad8dac793f87ba615cbe17d8d5a56d9381bae2d9b547c39
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
