apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-wvvq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-wvvq
    app.kubernetes.io/part-of: load-app-89b6afed-07cd-44a1-a6e2-cd64c48c9d36
  name: devfile-sample-wvvq
spec:
  ports:
  - port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-wvvq
status:
  loadBalancer: {}
